# for building pre-compiled image from Ubuntu (modded and pushed to repo)
FROM ubuntu:18.04
RUN apt-get upgrade && apt-get update && apt-get install -y sudo tar make vim python3.6
# RUN pip3 install -y pillow tensorflow
